@startuml
'https://plantuml.com/class-diagram
'nx console to help pre build tooling targets
interface IView {
+IEnumerable<IView> GetAllChildViews(bool includeAllDescendants)
}

abstract AbstractViewAdapter implements IView {
}

class InnerView extends AbstractViewAdapter

interface ITopLevelPresenter {
+ IEnumerable<IView> GetAllOwnedViews(bool includeAllDescendants) 
}

class ServerPagePresenter implements ITopLevelPresenter {
+ IEnumerable<IView> GetAllOwnedViews(bool includeAllDescendants) 
}

@enduml